'use strict';
(function(){
  var key='', data=null, siteSlots={home:[],guidebook:[]}, overrides={collection:{},property:{},rooms:{},site:{}};
  var status=document.getElementById('status'), management=document.getElementById('management');
  var collectionGrid=document.getElementById('collectionGrid'), propertyGrid=document.getElementById('propertyGrid');
  var pageHeroImages=document.getElementById('pageHeroImages'), welcomePopupImage=document.getElementById('welcomePopupImage'), homeHeroImages=document.getElementById('homeHeroImages'), homeSiteImages=document.getElementById('homeSiteImages'), guidebookSiteImages=document.getElementById('guidebookSiteImages');
  var rooms=document.getElementById('rooms'), photoRooms=document.getElementById('photoRooms'), imageMatrix=document.getElementById('imageMatrix');
  function esc(s){return String(s==null?'':s).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
  function money(v){return new Intl.NumberFormat('vi-VN').format(+v||0)+' ₫';}
  function setStatus(t,ok){status.className='status '+(ok?'ok':'err');status.textContent=t;}
  function toast(t){var el=document.getElementById('toast');el.textContent=t;el.style.display='block';clearTimeout(toast._t);toast._t=setTimeout(function(){el.style.display='none';},2400);}
  function api(url,opts){opts=opts||{};opts.headers=Object.assign({'x-admin-key':key},opts.headers||{});return fetch(url,opts).then(function(r){return r.json().then(function(x){if(!r.ok)throw new Error(x.error||'Có lỗi.');return x;});});}
  function roomRows(){var arr=[];(data.branches||[]).forEach(function(b){(b.rooms||[]).forEach(function(r){arr.push({branch:b,room:r});});});return arr;}
  function sourceMeta(id){return window.KAS_IMAGES&&window.KAS_IMAGES.meta?window.KAS_IMAGES.meta(id):{};}
  function sourceUrls(id){var c=window.KAS_IMAGES&&window.KAS_IMAGES.CATALOGUE?window.KAS_IMAGES.CATALOGUE[id]:null;if(!c)return [];function urls(a){return (a||[]).map(function(x){return window.KAS_IMAGES.url(x,960,660);});}return [].concat(urls(c.rooms),urls(c.exterior),urls(c.dining),urls(c.publicAreas),urls(c.leisure),urls(c.raw),urls(c.uncategorised));}
  function renderImageMatrix(){
    imageMatrix.innerHTML=(data.branches||[]).map(function(b){var m=sourceMeta(b.hotelId),urls=sourceUrls(b.hotelId);var cats=m.counts||{};return '<article class="matrixCard"><h3>'+esc(b.address)+' <span class="badge">'+esc(b.hotelId)+'</span></h3><div class="counts">Rooms '+(cats.rooms||0)+' · Exterior '+(cats.exterior||0)+' · Dining '+(cats.dining||0)+' · Public '+(cats.publicAreas||0)+' · Leisure '+(cats.leisure||0)+'</div><div class="sourceBox"><div class="sourceTop"><span class="small">Nguồn ảnh</span>'+(m.sourceUrl?'<a class="small" target="_blank" rel="noopener" href="'+esc(m.sourceUrl)+'">Mở nguồn ↗</a>':'')+'</div><div class="small">'+esc(m.source||'Chưa khai báo nguồn')+'</div><details><summary>Xem toàn bộ '+urls.length+' link ảnh</summary><div>'+urls.map(function(u,i){return '<a target="_blank" rel="noopener" href="'+esc(u)+'" title="'+esc(u)+'">'+(i+1)+'. '+esc(u)+'</a>';}).join('')+'</div></details></div></article>';}).join('');
  }
  function mergeList(scope,id,uploaded){var custom=(overrides[scope]&&overrides[scope][id])||[];if(scope==='collection')return custom.length?custom:[uploaded?{id:'uploaded',url:uploaded,source:'upload'}:null].filter(Boolean);return custom.length?custom:(uploaded||[]).map(function(x){var y=Object.assign({},x);y.source=y.source||'upload';return y;});}
  function imageThumb(x,delScope,delKey){var url=typeof x==='string'?x:x.url||'';var id=typeof x==='string'?'':x.id||'';var source=typeof x==='string'?'url':(x.source||'url');var action='';if(id&&id!=='uploaded'){if(source==='upload')action='<button class="btn danger" style="padding:4px 6px;font-size:10px" data-upload-delete-scope="'+esc(delScope)+'" data-upload-delete-id="'+esc(id)+'">Xóa</button>';else action='<button class="btn danger" style="padding:4px 6px;font-size:10px" data-url-delete="'+esc(delScope)+'" data-url-key="'+esc(delKey)+'" data-url-id="'+esc(id)+'">Xóa</button>';}return '<div class="thumb"><img src="'+esc(url)+'" alt=""><div class="tBody"><a target="_blank" rel="noopener" href="'+esc(url)+'" title="'+esc(url)+'">Mở / copy link</a><div><span class="source">'+esc((x.name||x.originalName||'URL').slice(0,22))+'</span>'+action+'</div></div></div>';}
  function urlInput(scope,id,label){return '<div class="urlRow"><input class="urlInput" data-url-input="'+esc(scope)+'" data-url-key="'+esc(id)+'" placeholder="'+esc(label||'https://...')+'"><button class="btn ghost" data-url-add="'+esc(scope)+'" data-url-key="'+esc(id)+'">Thêm URL</button></div>';}
  function bindUrlActions(root){
    root.querySelectorAll('[data-url-add]').forEach(function(btn){btn.addEventListener('click',function(){var scope=btn.dataset.urlAdd,id=btn.dataset.urlKey,input=root.querySelector('[data-url-input="'+CSS.escape(scope)+'"][data-url-key="'+CSS.escape(id)+'"]');var url=(input&&input.value||'').trim();if(!/^https:\/\//i.test(url)){toast('URL ảnh phải bắt đầu bằng https://');return;}btn.disabled=true;api('/api/admin/image-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:scope,key:id,url:url,name:'URL image',category:(root.querySelector('[data-url-category=\"'+CSS.escape(id)+'\"]')||root.querySelector('[data-property-category=\"'+CSS.escape(id)+'\"]')||{}).value||'other'})}).then(function(){toast('Đã thêm URL ảnh.');return load();}).catch(function(e){setStatus(e.message,false);}).finally(function(){btn.disabled=false;});});});
    root.querySelectorAll('[data-url-delete]').forEach(function(btn){btn.addEventListener('click',function(){if(!confirm('Xóa URL ảnh này khỏi website?'))return;api('/api/admin/image-url/'+encodeURIComponent(btn.dataset.urlDelete)+'/'+encodeURIComponent(btn.dataset.urlKey)+'/'+encodeURIComponent(btn.dataset.urlId),{method:'DELETE'}).then(function(){toast('Đã xóa URL ảnh.');return load();}).catch(function(e){setStatus(e.message,false);});});});
    root.querySelectorAll('[data-upload-delete-scope]').forEach(function(btn){btn.addEventListener('click',function(){var scope=btn.dataset.uploadDeleteScope,id=btn.dataset.uploadDeleteId;if(!confirm('Xóa ảnh upload này?'))return;var endpoint=scope==='property'?'/api/admin/property-images/':scope==='rooms'?'/api/admin/upload/':scope==='site'?'/api/admin/site-image/':'';if(!endpoint)return;api(endpoint+encodeURIComponent(id),{method:'DELETE'}).then(function(){toast('Đã xóa ảnh upload.');return load();}).catch(function(e){setStatus(e.message,false);});});});
  }
  function renderSiteImages(target, slots){
    if(!target) return;
    var siteOverrides=overrides.site||{};
    target.innerHTML=(slots||[]).map(function(slot){
      var item=siteOverrides[slot.key];
      var overrideUrl=item&&item.url?String(item.url):'';
      var current=overrideUrl||String(slot.default||'');
      var source=item?(item.source==='admin-upload'?'Ảnh upload trong Admin':'URL ghi đè từ Admin'):(slot.default?'Ảnh mặc định đang khai báo trên Website':'Chưa khai báo nguồn ảnh');
      var currentLink=current?'<a class="default" target="_blank" rel="noopener" href="'+esc(current)+'" title="'+esc(current)+'">Mở / copy link ảnh đang dùng ↗</a>':'';
      return '<article class="siteCard"><div class="media">'+(current?'<img src="'+esc(current)+'" alt="'+esc(slot.label)+'" loading="lazy">':'<div class="small">Chưa có ảnh</div>')+'</div><div class="body"><h3>'+esc(slot.label)+'</h3><div class="current">Nguồn hiện hành: '+esc(source)+'</div>'+currentLink+'<div class="upload"><input class="file" type="file" accept="image/jpeg,image/png,image/webp" data-site-input="'+esc(slot.key)+'"><button class="btn gold" data-site-upload="'+esc(slot.key)+'">Upload / thay ảnh</button></div>'+urlInput('site',slot.key,'https://link-anh...')+'<div class="thumbs">'+(item?imageThumb(item,'site',slot.key):'')+'</div></div></article>';
    }).join('');
    bindUrlActions(target);
    target.querySelectorAll('[data-site-upload]').forEach(function(btn){btn.addEventListener('click',function(){var id=btn.dataset.siteUpload,input=target.querySelector('[data-site-input="'+CSS.escape(id)+'"]');if(!input||!input.files.length){toast('Hãy chọn ảnh.');return;}var fd=new FormData();fd.append('key',id);fd.append('image',input.files[0]);btn.disabled=true;api('/api/admin/site-image',{method:'POST',body:fd}).then(function(){toast('Đã cập nhật ảnh '+id+'.');return load();}).catch(function(e){setStatus(e.message,false);}).finally(function(){btn.disabled=false;});});});
  }

  function renderCollections(){
    collectionGrid.innerHTML=(data.branches||[]).map(function(b){
      var uploaded=(data.collectionImages||{})[b.hotelId],imgs=mergeList('collection',b.hotelId,uploaded),mapped=!!b.propertyHeroId;
      return '<article class="collectionCard"><div class="media">'+(imgs.length?'<img src="'+esc(imgs[0].url||imgs[0])+'" alt="">':'<div class="small">Chưa có ảnh Collection</div>')+'</div><div class="body"><h3>'+esc(b.address)+'</h3><div class="small">'+esc(b.hotelId)+' · '+(mapped?'Ảnh Collection đang lấy từ Hero gallery':'Chưa mapping Hero')+'</div>'+ (mapped?'<div class="current">Hero: '+esc(b.propertyHeroUrl||'')+'</div>':'') +'<div class="upload"><input class="file" type="file" accept="image/jpeg,image/png,image/webp" data-collection-input="'+esc(b.hotelId)+'"><button class="btn gold" data-collection-upload="'+esc(b.hotelId)+'">Thay bằng file</button></div>'+urlInput('collection',b.hotelId,'https://link-anh-collection...')+'<div class="thumbs">'+imgs.map(function(x){return imageThumb(x,'collection',b.hotelId);}).join('')+'</div>'+((uploaded&&!mapped&&!(overrides.collection&&overrides.collection[b.hotelId]))?'<div class="rowActions"><button class="btn danger" data-collection-delete="'+esc(b.hotelId)+'">Xóa ảnh upload / về mặc định</button></div>':'')+'</div></article>';
    }).join('');
    bindUrlActions(collectionGrid);
    collectionGrid.querySelectorAll('[data-collection-upload]').forEach(function(btn){btn.addEventListener('click',function(){var id=btn.dataset.collectionUpload,input=collectionGrid.querySelector('[data-collection-input="'+CSS.escape(id)+'"]');if(!input||!input.files.length){toast('Hãy chọn ảnh Collection.');return;}var fd=new FormData();fd.append('hotelId',id);fd.append('image',input.files[0]);btn.disabled=true;api('/api/admin/collection-image',{method:'POST',body:fd}).then(function(){toast('Đã cập nhật ảnh Collection.');return load();}).catch(function(e){setStatus(e.message,false);}).finally(function(){btn.disabled=false;});});});
    collectionGrid.querySelectorAll('[data-collection-delete]').forEach(function(btn){btn.addEventListener('click',function(){if(!confirm('Xóa ảnh Collection upload và quay về ảnh mặc định?'))return;api('/api/admin/collection-image/'+encodeURIComponent(btn.dataset.collectionDelete),{method:'DELETE'}).then(function(){toast('Đã xóa ảnh Collection upload.');return load();}).catch(function(e){setStatus(e.message,false);});});});
  }
  function renderPropertyGallery(){
    var categoryLabels={rooms:'Phòng nghỉ',lobby:'Sảnh & Lễ tân',dining:'Nhà hàng & Ăn uống',exterior:'Ngoại thất',amenities:'Tiện ích',other:'Khác'};
    propertyGrid.innerHTML=(data.branches||[]).map(function(b){
      var uploaded=b.propertyImages||[],imgs=mergeList('property',b.hotelId,uploaded),heroId=b.propertyHeroId||'';
      var ordered=imgs.map(function(x){return typeof x==='string'?{url:x}:x;});
      var thumbs=ordered.map(function(x,i){
        var id=x.id||'' ,isHero=!!id&&id===heroId;
        return '<div class="thumb propertyThumb" draggable="'+(id?'true':'false')+'" data-property-thumb="'+esc(id)+'" data-hero="'+(isHero?'true':'false')+'">'+
          '<span class="propertyOrder">'+(i+1)+'</span>'+(isHero?'<span class="propertyHero">HERO · COLLECTION</span>':'')+
          '<img src="'+esc(x.url||'')+'" alt="" loading="lazy"><div class="tBody"><a target="_blank" rel="noopener" href="'+esc(x.url||'')+'" title="'+esc(x.url||'')+'">Mở / copy link</a><div><span class="source">'+esc((x.name||x.originalName||categoryLabels[x.category]||'URL').slice(0,22))+'</span></div><div class="small">'+esc(categoryLabels[x.category]||'Khác')+'</div><div class="propertyThumbActions">'+(isHero?'<button class="btn ghost" disabled>Đang là Hero</button>':'<button class="btn gold" data-property-hero="'+esc(x.id||'')+'">Đặt làm Hero</button>')+'</div></div></div>';
      }).join('');
      return '<article class="collectionCard propertyGalleryCard"><div class="media">'+(ordered.length?'<img src="'+esc(ordered[0].url||'')+'" alt="Ảnh Hero '+esc(b.address)+'" loading="lazy">':'<div class="small">Chưa có gallery riêng</div>')+'</div><div class="body"><h3>'+esc(b.address)+'</h3><div class="propertyMeta"><span class="small">'+esc(b.hotelId)+'</span><span class="galleryCount">'+ordered.length+' ảnh</span></div><div class="small" style="margin-bottom:8px">Kéo thả để đổi thứ tự. Ảnh có nhãn <b>HERO · COLLECTION</b> là ảnh dùng cho Hero khách sạn và KAS Collection.</div><div class="upload"><input class="file" type="file" accept="image/jpeg,image/png,image/webp" multiple data-property-input="'+esc(b.hotelId)+'"><select class="input" aria-label="Danh mục áp dụng cho upload và URL" data-property-category="'+esc(b.hotelId)+'"><option value="rooms">Phòng nghỉ</option><option value="lobby">Sảnh & Lễ tân</option><option value="dining">Nhà hàng & Ăn uống</option><option value="exterior">Ngoại thất</option><option value="amenities">Tiện ích</option><option value="other">Khác</option></select><button class="btn gold" data-property-upload="'+esc(b.hotelId)+'">Upload file</button></div>'+urlInput('property',b.hotelId,'https://link-anh-gallery...')+'<div class="propertyOrderedThumbs thumbs" data-property-list="'+esc(b.hotelId)+'">'+thumbs+'</div></div></article>';
    }).join('');
    bindUrlActions(propertyGrid);
    propertyGrid.querySelectorAll('[data-property-upload]').forEach(function(btn){btn.addEventListener('click',function(){var id=btn.dataset.propertyUpload,input=propertyGrid.querySelector('[data-property-input="'+CSS.escape(id)+'"]'),select=propertyGrid.querySelector('[data-property-category="'+CSS.escape(id)+'"]');if(!input||!input.files.length){toast('Hãy chọn ảnh gallery.');return;}if(input.files.length>20){toast('Mỗi lần tối đa 20 ảnh.');return;}var fd=new FormData();fd.append('hotelId',id);fd.append('category',select?select.value:'other');Array.prototype.forEach.call(input.files,function(f){fd.append('images',f);});btn.disabled=true;api('/api/admin/property-images',{method:'POST',body:fd}).then(function(x){toast('Đã upload '+x.added+' ảnh vào danh mục.');return load();}).catch(function(e){setStatus(e.message,false);}).finally(function(){btn.disabled=false;});});});
    propertyGrid.querySelectorAll('[data-property-hero]').forEach(function(btn){btn.addEventListener('click',function(){var card=btn.closest('.propertyGalleryCard'),hotelId=card&&card.querySelector('[data-property-list]')?card.querySelector('[data-property-list]').dataset.propertyList:'',imageId=btn.dataset.propertyHero;if(!hotelId||!imageId)return;btn.disabled=true;api('/api/admin/property-images/hero',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({hotelId:hotelId,imageId:imageId})}).then(function(){toast('Đã đặt Hero và đồng bộ KAS Collection.');return load();}).catch(function(e){setStatus(e.message,false);}).finally(function(){btn.disabled=false;});});});
    propertyGrid.querySelectorAll('[data-property-list]').forEach(function(list){
      var dragId='';
      list.querySelectorAll('[data-property-thumb]').forEach(function(item){
        item.addEventListener('dragstart',function(e){if(!item.dataset.propertyThumb)return;dragId=item.dataset.propertyThumb;item.classList.add('is-dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragId);});
        item.addEventListener('dragend',function(){item.classList.remove('is-dragging');dragId='';});
        item.addEventListener('dragover',function(e){e.preventDefault();e.dataTransfer.dropEffect='move';});
        item.addEventListener('drop',function(e){e.preventDefault();var from=dragId||e.dataTransfer.getData('text/plain'),to=item.dataset.propertyThumb;if(!from||!to||from===to)return;var nodes=Array.prototype.slice.call(list.querySelectorAll('[data-property-thumb]')),ids=nodes.map(function(n){return n.dataset.propertyThumb;}),fromIndex=ids.indexOf(from),toIndex=ids.indexOf(to);if(fromIndex<0||toIndex<0)return;ids.splice(fromIndex,1);ids.splice(toIndex,0,from);var hotelId=list.dataset.propertyList;api('/api/admin/property-images/order',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({hotelId:hotelId,order:ids})}).then(function(){toast('Đã lưu thứ tự ảnh.');return load();}).catch(function(e){setStatus(e.message,false);});});
      });
    });
  }
  function priceInput(k,s,i,v,l){return '<label>'+l+'<input type="number" min="0" step="50000" data-rate="'+esc(k)+'" data-season="'+s+'" data-idx="'+i+'" value="'+esc(v)+'"></label>';}
  function seasonBox(r,s,t){var p=r.rates[s];return '<div class="seasonBox"><div class="seasonTitle">'+t+'</div><div class="priceInputs">'+priceInput(r.key,s,0,p[0],'Trong tuần')+priceInput(r.key,s,1,p[1],'Cuối tuần')+'</div></div>';}
  function renderRooms(filter){var q=(filter||'').trim().toLowerCase();var arr=roomRows().filter(function(x){var b=x.branch,r=x.room;return !q||[b.address,b.hotelId,r.stt,r.ez,r.name].join(' ').toLowerCase().indexOf(q)>-1;});rooms.innerHTML=arr.map(function(x){var b=x.branch,r=x.room;return '<article class="room"><div class="roomHead"><div><h3>'+esc(b.address)+' · STT '+esc(r.stt)+' · '+esc(r.name)+'</h3><div class="meta">Ez: '+esc(r.ez)+' · Mã room: '+esc(r.key)+'</div></div><div class="galleryCount">'+money(r.rates.jul_sep[0])+' / '+money(r.rates.jul_sep[1])+' · Jul–Sep</div></div><div class="priceGrid">'+seasonBox(r,'jul_sep','Tháng 7–9')+seasonBox(r,'oct','Tháng 10')+seasonBox(r,'nov_jan','Tháng 11–1/2027')+'</div><div class="saveRow"><button class="btn gold" data-save-rate="'+esc(r.key)+'">Lưu giá</button></div></article>';}).join('');rooms.querySelectorAll('[data-save-rate]').forEach(function(btn){btn.addEventListener('click',function(){saveRates(btn.dataset.saveRate,btn);});});}
  function saveRates(k,btn){var rates={};['jul_sep','oct','nov_jan'].forEach(function(s){rates[s]=[0,1].map(function(i){var el=document.querySelector('[data-rate="'+CSS.escape(k)+'"][data-season="'+s+'"][data-idx="'+i+'"]');return Number(el.value||0);});});btn.disabled=true;api('/api/admin/room-rates',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomKey:k,rates:rates})}).then(function(){toast('Đã lưu giá '+k);return load();}).catch(function(e){setStatus(e.message,false);}).finally(function(){btn.disabled=false;});}
  function renderPhotos(){
    photoRooms.innerHTML=(data.branches||[]).map(function(b){return '<section class="room"><div class="roomHead"><div><h3>'+esc(b.address)+'</h3><div class="meta">'+b.rooms.length+' hạng phòng</div></div></div>'+b.rooms.map(function(r){var uploaded=r.images||[],imgs=mergeList('rooms',r.key,uploaded);return '<div style="border-top:1px solid var(--line);padding-top:13px;margin-top:13px"><div class="roomHead"><div><b>STT '+esc(r.stt)+' · '+esc(r.name)+'</b><div class="meta">Ez: '+esc(r.ez)+' · '+esc(r.key)+'</div></div><span class="galleryCount">'+imgs.length+' ảnh hiện hành</span></div><div class="upload"><input class="file" type="file" accept="image/jpeg,image/png,image/webp" multiple data-room="'+esc(r.key)+'"><button class="btn gold" data-upload="'+esc(r.key)+'">Upload file</button></div>'+urlInput('rooms',r.key,'https://link-anh-room...')+'<div class="thumbs">'+imgs.map(function(x){return imageThumb(x,'rooms',r.key);}).join('')+'</div></div>';}).join('')+'</section>';}).join('');
    bindUrlActions(photoRooms);
    photoRooms.querySelectorAll('[data-upload]').forEach(function(btn){btn.addEventListener('click',function(){var k=btn.dataset.upload,input=photoRooms.querySelector('input[data-room="'+CSS.escape(k)+'"]');if(!input||!input.files.length){toast('Hãy chọn ảnh phòng.');return;}var fd=new FormData();fd.append('roomKey',k);Array.prototype.forEach.call(input.files,function(f){fd.append('images',f);});btn.disabled=true;api('/api/admin/upload',{method:'POST',body:fd}).then(function(x){toast('Đã upload '+x.added+' ảnh.');return load();}).catch(function(e){setStatus(e.message,false);}).finally(function(){btn.disabled=false;});});});
  }
  function render(){renderImageMatrix();
    renderSiteImages(homeHeroImages,siteSlots.homeHero||[]);
    renderSiteImages(pageHeroImages,(siteSlots.pageHero||[]).filter(function(slot){return slot.key!=='page.hero.welcome';}));
    renderSiteImages(welcomePopupImage,(siteSlots.pageHero||[]).filter(function(slot){return slot.key==='page.hero.welcome';}));
    renderSiteImages(homeSiteImages,siteSlots.home||[]);
    renderSiteImages(guidebookSiteImages,siteSlots.guidebook||[]);
    renderCollections();renderPropertyGallery();renderRooms(document.getElementById('roomSearch').value);renderPhotos();}
  function load(){return Promise.all([fetch('/api/catalog',{cache:'no-store'}).then(function(r){return r.json();}),api('/api/admin/image-overrides'),fetch('/site-image-slots.json',{cache:'no-store'}).then(function(r){return r.json();})]).then(function(xs){data=xs[0];overrides=xs[1]||{collection:{},property:{},rooms:{},site:{}};if(!overrides.site)overrides.site={};siteSlots=xs[2]||{home:[],guidebook:[],pageHero:[]};render();});}
  document.getElementById('roomSearch').addEventListener('input',function(){renderRooms(this.value);});
  document.getElementById('login').addEventListener('click',function(){key=document.getElementById('key').value.trim();var localNoKey=location.hostname==='localhost'||location.hostname==='127.0.0.1'||location.hostname==='[::1]';if(!key&&!localNoKey){setStatus('Hãy nhập ADMIN_KEY.',false);return;}api('/api/admin/status').then(function(){setStatus('Đã mở quyền quản trị.',true);management.classList.remove('hidden');document.getElementById('publicBox').classList.remove('hidden');document.getElementById('publicUrl').textContent=location.origin+'/index.html';document.getElementById('referenceUrl').textContent=location.origin+'/reference';return load();}).catch(function(e){setStatus(e.message,false);});});
})();
